//Generated by Material Mapping

using System;
using System.Collections.Generic;
using Plugins.CarX.Modding.Runtime;
using UnityEngine;

namespace Plugins.CarX.Modding.Creator.Generation
{
    public class MaterialMapping
    {
        public static MaterialMapping mapping;

        [Serializable]
        public struct MaterialData
        {
            public string propertyName;
            public int propertyType;
            public string comment;
            public Action<string, object, Material> action;
        }

        public readonly IReadOnlyDictionary<string, MaterialData[]> map = new Dictionary<string, MaterialData[]>()
        {
        };

    }
}
