// Generated by Material Mapping Editor
// Do not edit manually

using System;
using System.Collections.Generic;
using UnityEngine;

namespace Plugins.CarX.Modding.Creator.Generation
{
	/// <summary>
	/// Generated abstract material mapping for MAT_ROUGHNESS_METALNESS_NORMAL_ALPHABLEND variant
	/// Implement mapping logic by deriving from this class and assigning the static 'mapping' field.
	/// </summary>
	public abstract class MatRoughnessMetalnessNormalAlphablend
	{
		public static MatRoughnessMetalnessNormalAlphablend mapping;

		protected MatRoughnessMetalnessNormalAlphablend(MatRoughnessMetalnessNormalAlphablend mapping)
		{
			MatRoughnessMetalnessNormalAlphablend.mapping = mapping;
		}

		[Serializable]
		public struct MaterialData
		{
			public string propertyName;
			public int propertyType; // as int to avoid direct enum coupling
			public Action<string, object, Material> action;
		}

		// Property keys
		public const string Key_u_sTexture = "u_sTexture";
		public const string Key_u_sPackedMap = "u_sPackedMap";
		public const string Key_u_sNormalMap = "u_sNormalMap";

		public readonly IReadOnlyDictionary<string, MaterialData[]> map = new Dictionary<string, MaterialData[]>()
		{
			{
				Key_u_sTexture, new []{
					new MaterialData
					{
						propertyType = 4,
						propertyName = "map_Kd",
						action = mapping == null ? null : ((n, v, m) => mapping.FromMapKd(n, (Texture2D)v, m))
					}
				}
			},
			{
				Key_u_sPackedMap, new []{
					new MaterialData
					{
						propertyType = 4,
						propertyName = "map_Pr",
						action = mapping == null ? null : ((n, v, m) => mapping.FromMapPr(n, (Texture2D)v, m))
					},
					new MaterialData
					{
						propertyType = 4,
						propertyName = "map_Pm",
						action = mapping == null ? null : ((n, v, m) => mapping.FromMapPm(n, (Texture2D)v, m))
					},
					new MaterialData
					{
						propertyType = 4,
						propertyName = "map_d",
						action = mapping == null ? null : ((n, v, m) => mapping.FromMapD(n, (Texture2D)v, m))
					}
				}
			},
			{
				Key_u_sNormalMap, new []{
					new MaterialData
					{
						propertyType = 4,
						propertyName = "bump",
						action = mapping == null ? null : ((n, v, m) => mapping.FromBump(n, (Texture2D)v, m))
					},
					new MaterialData
					{
						propertyType = 4,
						propertyName = "map_bump",
						action = mapping == null ? null : ((n, v, m) => mapping.FromMapBump(n, (Texture2D)v, m))
					},
					new MaterialData
					{
						propertyType = 4,
						propertyName = "norm",
						action = mapping == null ? null : ((n, v, m) => mapping.FromNorm(n, (Texture2D)v, m))
					}
				}
			},
		};


		/// <summary>
		/// Handles mapping for the 'map_Kd' property.
		/// This method is generated and should not be modified.
		/// </summary>
		public void FromMapKd(string name, Texture2D mapKd, Material property)
		{
			switch (name)
			{
				case "u_sTexture":
					usTextureFromMapKd(name, mapKd, property);
					break;
			}
		}

		/// <summary>
		/// Handles mapping for the 'map_Pr' property.
		/// This method is generated and should not be modified.
		/// </summary>
		public void FromMapPr(string name, Texture2D mapPr, Material property)
		{
			switch (name)
			{
				case "u_sPackedMap":
					usPackedMapFromMapPr(name, mapPr, property);
					usPackedMapFromMapPm(name, mapPr, property);
					usPackedMapFromMapD(name, mapPr, property);
					break;
			}
		}

		/// <summary>
		/// Handles mapping for the 'map_Pm' property.
		/// This method is generated and should not be modified.
		/// </summary>
		public void FromMapPm(string name, Texture2D mapPm, Material property)
		{
			switch (name)
			{
				case "u_sPackedMap":
					usPackedMapFromMapPr(name, mapPm, property);
					usPackedMapFromMapPm(name, mapPm, property);
					usPackedMapFromMapD(name, mapPm, property);
					break;
			}
		}

		/// <summary>
		/// Handles mapping for the 'map_d' property.
		/// This method is generated and should not be modified.
		/// </summary>
		public void FromMapD(string name, Texture2D mapD, Material property)
		{
			switch (name)
			{
				case "u_sPackedMap":
					usPackedMapFromMapPr(name, mapD, property);
					usPackedMapFromMapPm(name, mapD, property);
					usPackedMapFromMapD(name, mapD, property);
					break;
			}
		}

		/// <summary>
		/// Handles mapping for the 'bump' property.
		/// This method is generated and should not be modified.
		/// </summary>
		public void FromBump(string name, Texture2D bump, Material property)
		{
			switch (name)
			{
				case "u_sNormalMap":
					usNormalMapFromBump(name, bump, property);
					usNormalMapFromMapBump(name, bump, property);
					usNormalMapFromNorm(name, bump, property);
					break;
			}
		}

		/// <summary>
		/// Handles mapping for the 'map_bump' property.
		/// This method is generated and should not be modified.
		/// </summary>
		public void FromMapBump(string name, Texture2D mapBump, Material property)
		{
			switch (name)
			{
				case "u_sNormalMap":
					usNormalMapFromBump(name, mapBump, property);
					usNormalMapFromMapBump(name, mapBump, property);
					usNormalMapFromNorm(name, mapBump, property);
					break;
			}
		}

		/// <summary>
		/// Handles mapping for the 'norm' property.
		/// This method is generated and should not be modified.
		/// </summary>
		public void FromNorm(string name, Texture2D norm, Material property)
		{
			switch (name)
			{
				case "u_sNormalMap":
					usNormalMapFromBump(name, norm, property);
					usNormalMapFromMapBump(name, norm, property);
					usNormalMapFromNorm(name, norm, property);
					break;
			}
		}

		/// <summary>
		/// Default diffuse/albedo texture.
		/// </summary>
		protected virtual void usTextureFromMapKd(string name, Texture2D uStexture, Material property)
		{
			property.SetTexture(name, uStexture);
		}

		/// <summary>
		/// Surface packed parameters. R - roughness, G - metalness, B - alpha, A - unused.
		/// </summary>
		protected virtual void usPackedMapFromMapPr(string name, Texture2D uSpackedmap, Material property)
		{
			property.SetTexture(name, uSpackedmap);
		}

		/// <summary>
		/// Surface packed parameters. R - roughness, G - metalness, B - alpha, A - unused.
		/// </summary>
		protected virtual void usPackedMapFromMapPm(string name, Texture2D uSpackedmap, Material property)
		{
			property.SetTexture(name, uSpackedmap);
		}

		/// <summary>
		/// Surface packed parameters. R - roughness, G - metalness, B - alpha, A - unused.
		/// </summary>
		protected virtual void usPackedMapFromMapD(string name, Texture2D uSpackedmap, Material property)
		{
			property.SetTexture(name, uSpackedmap);
		}

		/// <summary>
		/// Texture of surface normals.
		/// </summary>
		protected virtual void usNormalMapFromBump(string name, Texture2D uSnormalmap, Material property)
		{
			property.SetTexture(name, uSnormalmap);
		}

		/// <summary>
		/// Texture of surface normals.
		/// </summary>
		protected virtual void usNormalMapFromMapBump(string name, Texture2D uSnormalmap, Material property)
		{
			property.SetTexture(name, uSnormalmap);
		}

		/// <summary>
		/// Texture of surface normals.
		/// </summary>
		protected virtual void usNormalMapFromNorm(string name, Texture2D uSnormalmap, Material property)
		{
			property.SetTexture(name, uSnormalmap);
		}
	}
}
